Bt 1720
nordicbraintech/ad-b2c-react-native pull request #11
Opened 2021-03-26 14:03 UTC by stefanab

Patch CVE-2021-27292

2021-04-07 12:55 UTC, Marvedog requested changes
Two errors after running `rm -rf node_modules && yarn cache clean && yarn install && yarn test`.

**Error 1**
Line 19 `LoginView.test.js`: `ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.`

**Error 2**
Line 93 `LoginView.test.js`:  Wrong output.

2021-04-07 13:58 UTC, stefanab commented
Error 1: Not introduced in this PR however.

Error 2: Not able to recreate. Sure you have the latest branch?

2021-04-07 18:14 UTC, Marvedog commented
> Error 1: Not introduced in this PR however.
Ok. Then this error should be fixed before next release, we can't have a repo with failing tests. 
> Error 2: Not able to recreate. Sure you have the latest branch?
Jupp. The error comes from this test it seems

```shell
FAIL  tests/LoginView.test.js
  ● LoginView › renders correctly when loaded

    TypeError: renderExitButton is not a function
```

2021-04-08 16:17 UTC, stefanab commented
hm yeah i agree. None of the tests are failing per se though. The problem comes from the `renderLoading` function in the `props`. It doesn't like that the `<Text>` component is rendered there or something. I've tried to resolve it with `jest.useFakeTimers()` as  [here](https://stackoverflow.com/questions/50793885/referenceerror-you-are-trying-to-import-a-file-after-the-jest-environment-has) with no luck

As for the second error i still can't recreate it.

2021-04-08 16:21 UTC, Marvedog approved these changes

2021-04-08 16:26 UTC, merged